### ISSUE TITLE
quad to parametric issue

### ISSUE THREAD

**Issue by isentropic** [chaaland/EllipseFit.jl#2]
Right now quad2parametric would not work in general, as there is a rule on how to order the eigenvalues when solving the equations.

Details in p17
http://www.cs.cornell.edu/cv/otherpdf/ellipse.pdf

**Comment by chaaland** [comment]
I think `acos(V[1,1])` should be `acos(V[1,2]/V[1,1])` but why does eigenvalue order matter? We always have the eigenvector with the largest eigenvalue first and just compute it's angle from the positive x-axis. If we used the smaller eigenvalue we'd get an equivalent representation just different values of a,b, and ccw_angle

**Comment by isentropic** [comment]
I'm not 100% sure where the issue is, but sometimes when I use quad2parametric I end up with "theta" angle when the correct would have been "-theta". It makes drawing the fitted ellipse with the not always correct angle.

**Comment by chaaland** [comment]
Oh I think I see the problem. Should be using a two argument version of arctangent. Have to know the sign of both the x and y component of the eigenvector. Good catch. Will be tied up at work starting now but feel free to issue another PR. I can also try after work
